# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

# This workflow will install Deno and run tests across stable and nightly builds on Windows, Ubuntu and macOS.
# For more information see: https://github.com/denolib/setup-deno

name: Build

env:
  APPLICATION_NAME: "YouTube Client"
  DEPLOY_PACKAGE_NAME: "youtube-client-ver-${{ github.sha }}"

on:
  push:
    branches: [development]
  pull_request:
    branches: [development]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x]
    
    steps:
      - name: Checkout
        uses: actions/checkout@v1
        
      - name: Use Node 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
                    
      - name: Install dependencies
        run: npm ci
        
      - name: Build
        run: npm run build:ci

      - name: Test
        run: npm run test:ci
        
      - name: Lint
        run: npm run lint

      - name: Archive build
        if: success()
        uses: actions/upload-artifact@v1
        with: 
          name: delploy_dist
          path: dist
  
  deploy:
    runs-on: ubuntu-latest
    needs: build
    
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      
      - name: Download build
        uses: actions/download-artifact@v1
        with:
          name: deploy_dist
        
      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            BRANCH: gh-pages
            FOLDER: deploy_dist/youtube-client
